
# Number Guessing Game
# Guess a random number generated by the program.

import random

# Step 1: Greet the user and ask for the difficulty level
print("Welcome to the Number Guessing Game!")
level = input("Choose a difficulty level (easy, medium, hard): ").lower()

# Step 2: Set the range of the random number based on difficulty
if level == "easy":
    number = random.randint(1, 10)
elif level == "medium":
    number = random.randint(1, 50)
else:
    number = random.randint(1, 100)

# Step 3: Prompt the user to guess the number until they get it right
guess = None
while guess != number:
    try:
        guess = int(input("Guess the number: "))
        if guess < number:
            print("Too low! Try again.")
        elif guess > number:
            print("Too high! Try again.")
        else:
            print("Congratulations! You guessed it!")
    except ValueError:
        print("Invalid input. Please enter a number.")
